import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { MenuProvider } from "@/contexts/ContextMenu";
import { Toaster } from "react-hot-toast";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<Script
			src="https://www.googletagmanager.com/gtag/js?id=G-MC2D7TTZEJ"
			strategy="afterInteractive"
		/>
		<Script id="google-analytics" strategy="afterInteractive">
			{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-MC2D7TTZEJ');
        `}
		</Script>
		<body className={`${inter.className} relative overflow-x-hidden`}>
		<MenuProvider>{children}</MenuProvider>
		<Toaster/>
		</body>
		</html>
	);
}
